/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import model.Address;
import model.Person;
import model.PersonDirectory;
import ui.UserManager.UserMngWorkAreaJPanel;

/**
 *
 * @author Reetika
 */
public class MainJFrame extends javax.swing.JFrame {
    
    private PersonDirectory personDirectory;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
        this.personDirectory = new PersonDirectory();
        generateDemoData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        topJPanel = new javax.swing.JPanel();
        btnPersonMng = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        splitPane.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 204), new java.awt.Color(204, 0, 204), new java.awt.Color(204, 0, 204), new java.awt.Color(204, 0, 204)));
        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        topJPanel.setBackground(new java.awt.Color(25, 29, 76));
        topJPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 204), new java.awt.Color(204, 0, 204), new java.awt.Color(204, 0, 204), new java.awt.Color(204, 0, 204)));

        btnPersonMng.setBackground(new java.awt.Color(102, 0, 102));
        btnPersonMng.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        btnPersonMng.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonMng.setText("Open Person Manager");
        btnPersonMng.setIconTextGap(5);
        btnPersonMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonMngActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topJPanelLayout = new javax.swing.GroupLayout(topJPanel);
        topJPanel.setLayout(topJPanelLayout);
        topJPanelLayout.setHorizontalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPersonMng, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
                .addContainerGap())
        );
        topJPanelLayout.setVerticalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPersonMng, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        splitPane.setTopComponent(topJPanel);

        userProcessContainer.setBackground(new java.awt.Color(102, 102, 102));
        userProcessContainer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 204), new java.awt.Color(204, 0, 204), new java.awt.Color(204, 0, 204), new java.awt.Color(204, 0, 204)));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonMngActionPerformed
        // TODO add your handling code here:
        UserMngWorkAreaJPanel panel = new UserMngWorkAreaJPanel(userProcessContainer, personDirectory);
        userProcessContainer.add("UserMngWorkAreaJPanel", panel);
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnPersonMngActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPersonMng;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel topJPanel;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables


    private void generateDemoData() {
        // Person 1
        Person person1 = personDirectory.addNewPerson();
        person1.setFirstName("Mansi");
        person1.setLastName("Doshi");
        person1.setPhoneNumber("1234567890");
        person1.setDateOfBirth("1990-01-01");
        person1.setSocialSecurityNumber(123456789L);
        person1.setAge(32);
        person1.setGender('F');
        person1.setSalary(85000.00);

        Address homeAddress1 = new Address();
        homeAddress1.setStreetName("Main St");
        homeAddress1.setUnitNumber("101");
        homeAddress1.setCityName("Mumbai");
        homeAddress1.setStateName("Maharashtra");
        homeAddress1.setZipCode("400082");
        homeAddress1.setPhoneNumber("9876543210");
        person1.setHomeAddress(homeAddress1);

        Address workAddress1 = new Address();
        workAddress1.setStreetName("Corporate Park");
        workAddress1.setUnitNumber("102");
        workAddress1.setCityName("Pune");
        workAddress1.setStateName("Maharashtra");
        workAddress1.setZipCode("789456");
        workAddress1.setPhoneNumber("9123456789");
        person1.setWorkAddress(workAddress1);

        // Person 2
        Person person2 = personDirectory.addNewPerson();
        person2.setFirstName("Janvi");
        person2.setLastName("Shah");
        person2.setPhoneNumber("1234567891");
        person2.setDateOfBirth("1991-02-02");
        person2.setSocialSecurityNumber(123456788L);
        person2.setAge(31);
        person2.setGender('F');
        person2.setSalary(90000.00);

        Address homeAddress2 = new Address();
        homeAddress2.setStreetName("Broadway");
        homeAddress2.setUnitNumber("202");
        homeAddress2.setCityName("Boston");
        homeAddress2.setStateName("Massachusetts");
        homeAddress2.setZipCode("201304");
        homeAddress2.setPhoneNumber("9876543211");
        person2.setHomeAddress(homeAddress2);

        Address workAddress2 = new Address();
        workAddress2.setStreetName("Wall St");
        workAddress2.setUnitNumber("203");
        workAddress2.setCityName("New York");
        workAddress2.setStateName("New York");
        workAddress2.setZipCode("789456");
        workAddress2.setPhoneNumber("9123456781");
        person2.setWorkAddress(workAddress2);

        // Person 3
        Person person3 = personDirectory.addNewPerson();
        person3.setFirstName("Meera");
        person3.setLastName("Mehta");
        person3.setPhoneNumber("1234567892");
        person3.setDateOfBirth("1989-03-03");
        person3.setSocialSecurityNumber(123456787L);
        person3.setAge(33);
        person3.setGender('F');
        person3.setSalary(95000.00);

        Address homeAddress3 = new Address();
        homeAddress3.setStreetName("Sunset Blvd");
        homeAddress3.setUnitNumber("303");
        homeAddress3.setCityName("Los Angeles");
        homeAddress3.setStateName("California");
        homeAddress3.setZipCode("890082");
        homeAddress3.setPhoneNumber("9876543212");
        person3.setHomeAddress(homeAddress3);

        Address workAddress3 = new Address();
        workAddress3.setStreetName("Magnificent Mile");
        workAddress3.setUnitNumber("304");
        workAddress3.setCityName("Chicago");
        workAddress3.setStateName("Illinois");
        workAddress3.setZipCode("258963");
        workAddress3.setPhoneNumber("9123456782");
        person3.setWorkAddress(workAddress3);

        // Person 4
        Person person4 = personDirectory.addNewPerson();
        person4.setFirstName("Reetika");
        person4.setLastName("Bhanushali");
        person4.setPhoneNumber("1234567893");
        person4.setDateOfBirth("1992-04-04");
        person4.setSocialSecurityNumber(123456786L);
        person4.setAge(30);
        person4.setGender('F');
        person4.setSalary(92000.00);

        Address homeAddress4 = new Address();
        homeAddress4.setStreetName("Elm St");
        homeAddress4.setUnitNumber("404");
        homeAddress4.setCityName("Houston");
        homeAddress4.setStateName("Texas");
        homeAddress4.setZipCode("579456");
        homeAddress4.setPhoneNumber("9876543213");
        person4.setHomeAddress(homeAddress4);

        Address workAddress4 = new Address();
        workAddress4.setStreetName("Camelback Rd");
        workAddress4.setUnitNumber("405");
        workAddress4.setCityName("Phoenix");
        workAddress4.setStateName("Arizona");
        workAddress4.setZipCode("367412");
        workAddress4.setPhoneNumber("9123456783");
        person4.setWorkAddress(workAddress4);

        // Person 5
        Person person5 = personDirectory.addNewPerson();
        person5.setFirstName("Rajvi");
        person5.setLastName("Patel");
        person5.setPhoneNumber("1234567894");
        person5.setDateOfBirth("1993-05-05");
        person5.setSocialSecurityNumber(123456785L);
        person5.setAge(29);
        person5.setGender('F');
        person5.setSalary(88000.00);

        Address homeAddress5 = new Address();
        homeAddress5.setStreetName("Market St");
        homeAddress5.setUnitNumber("505");
        homeAddress5.setCityName("Philadelphia");
        homeAddress5.setStateName("Pennsylvania");
        homeAddress5.setZipCode("548961");
        homeAddress5.setPhoneNumber("9876543214");
        person5.setHomeAddress(homeAddress5);

        Address workAddress5 = new Address();
        workAddress5.setStreetName("River Walk");
        workAddress5.setUnitNumber("506");
        workAddress5.setCityName("San Antonio");
        workAddress5.setStateName("Texas");
        workAddress5.setZipCode("357469");
        workAddress5.setPhoneNumber("9123456784");
        person5.setWorkAddress(workAddress5);
    }

}
