/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import model.Address;
import model.Person;
import model.PersonDirectory;
import ui.UserManager.UserMngWorkAreaJPanel;

/**
 *
 * @author Reetika
 */
public class MainJFrame extends javax.swing.JFrame {
    
    private PersonDirectory personDirectory;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
        this.personDirectory = new PersonDirectory();
        generateDemoData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        topJPanel = new javax.swing.JPanel();
        btnPersonMng = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        splitPane.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 204), new java.awt.Color(204, 0, 204), new java.awt.Color(204, 0, 204), new java.awt.Color(204, 0, 204)));
        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        topJPanel.setBackground(new java.awt.Color(25, 29, 76));
        topJPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 204), new java.awt.Color(204, 0, 204), new java.awt.Color(204, 0, 204), new java.awt.Color(204, 0, 204)));

        btnPersonMng.setBackground(new java.awt.Color(102, 0, 102));
        btnPersonMng.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        btnPersonMng.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonMng.setText("Open Person Manager");
        btnPersonMng.setIconTextGap(5);
        btnPersonMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonMngActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topJPanelLayout = new javax.swing.GroupLayout(topJPanel);
        topJPanel.setLayout(topJPanelLayout);
        topJPanelLayout.setHorizontalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPersonMng, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                .addContainerGap())
        );
        topJPanelLayout.setVerticalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPersonMng, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        splitPane.setTopComponent(topJPanel);

        userProcessContainer.setBackground(new java.awt.Color(102, 102, 102));
        userProcessContainer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 204), new java.awt.Color(204, 0, 204), new java.awt.Color(204, 0, 204), new java.awt.Color(204, 0, 204)));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(splitPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonMngActionPerformed
        // TODO add your handling code here:
        UserMngWorkAreaJPanel panel = new UserMngWorkAreaJPanel(userProcessContainer, personDirectory);
        userProcessContainer.add("UserMngWorkAreaJPanel", panel);
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnPersonMngActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPersonMng;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel topJPanel;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables


    private void generateDemoData() {
        
        Person person1 = personDirectory.addNewPerson();
        person1.setFirstName("Mansi");
        person1.setLastName("Doshi");
        
        Address homeAddress1 = new Address();
        homeAddress1.setCityName("Mumbai");
        homeAddress1.setZipCode("400082");
        person1.setHomeAddress(homeAddress1);
        
        Address workAddress1 = new Address();
        workAddress1.setCityName("Pune");
        workAddress1.setZipCode("789456");
        person1.setWorkAddress(workAddress1);
        
        
        Person person2 = personDirectory.addNewPerson();
        person2.setFirstName("Janvi");
        person2.setLastName("Shah");
        
        Address homeAddress2 = new Address();
        homeAddress2.setCityName("Boston");
        homeAddress2.setZipCode("201304");
        person1.setHomeAddress(homeAddress2);
        
        Address workAddress2 = new Address();
        workAddress2.setCityName("New York");
        workAddress2.setZipCode("789456");
        person2.setWorkAddress(workAddress2);
        
        
        Person person3 = personDirectory.addNewPerson();
        person3.setFirstName("Meera");
        person3.setLastName("Mehta");
        
        Address homeAddress3 = new Address();
        homeAddress3.setCityName("Los Angeles");
        homeAddress3.setZipCode("890082");
        person3.setHomeAddress(homeAddress3);
        
        Address workAddress3 = new Address();
        workAddress3.setCityName("Chicago");
        workAddress3.setZipCode("258963");
        person3.setWorkAddress(workAddress3);
        
        Person person4 = personDirectory.addNewPerson();
        person4.setFirstName("Reetika");
        person4.setLastName("Bhanushali");
        
        Address homeAddress4 = new Address();
        homeAddress4.setCityName("Houston");
        homeAddress4.setZipCode("579456");
        person4.setHomeAddress(homeAddress4);
        
        Address workAddress4 = new Address();
        workAddress4.setCityName("Pheonix");
        workAddress4.setZipCode("367412");
        person1.setWorkAddress(workAddress4);
        
        Person person5 = personDirectory.addNewPerson();
        person5.setFirstName("Rajvi");
        person5.setLastName("Patel");
        
        Address homeAddress5 = new Address();
        homeAddress5.setCityName("Philadelphia");
        homeAddress5.setZipCode("548961");
        person5.setHomeAddress(homeAddress5);
        
        Address workAddress5 = new Address();
        workAddress5.setCityName("San Antonio");
        workAddress5.setZipCode("357469");
        person5.setWorkAddress(workAddress5);
        
        
        Person person6 = personDirectory.addNewPerson();
        person6.setFirstName("Shrusti");
        person6.setLastName("Suvarna");
        
        Address homeAddress6 = new Address();
        homeAddress6.setCityName("San Diego");
        homeAddress6.setZipCode("397845");
        person6.setHomeAddress(homeAddress6);
        
        Address workAddress6 = new Address();
        workAddress6.setCityName("San Jose");
        workAddress6.setZipCode("885544");
        person6.setWorkAddress(workAddress6);
        
        
    }
}
