/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.UserManager;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Address;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author Reetika
 */
public class NewPersonJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    PersonDirectory personDirectory;

    /**
     * Creates new form NewPerson
     */
    public NewPersonJPanel(JPanel container, PersonDirectory directory) {
        initComponents();
        
        userProcessContainer = container;
        personDirectory = directory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddNewPerson = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        lblDateOfBirth = new javax.swing.JLabel();
        txtDateOfBirth = new javax.swing.JTextField();
        lblSsn = new javax.swing.JLabel();
        txtSsn = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblPhoneNumber = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblSalary = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        lblHomeAddress = new javax.swing.JLabel();
        lblWorkAddress = new javax.swing.JLabel();
        lblStreetNameHomeAddress = new javax.swing.JLabel();
        lblUnitNumberHomeAddress = new javax.swing.JLabel();
        lblCityNameHomeAddress = new javax.swing.JLabel();
        lblStateNameHomeAddress = new javax.swing.JLabel();
        lblZipCodeHomeAddress = new javax.swing.JLabel();
        lblPhoneNumberHomeAddress = new javax.swing.JLabel();
        txtStreetNameHomeAddress = new javax.swing.JTextField();
        txtUnitNumberHomeAddress = new javax.swing.JTextField();
        txtCityNameHomeAddress = new javax.swing.JTextField();
        txtStateNameHomeAddress = new javax.swing.JTextField();
        txtPhoneNumberHomeAddress = new javax.swing.JTextField();
        txtZipCodeHomeAddress = new javax.swing.JTextField();
        txtStreetNameWorkAddress = new javax.swing.JTextField();
        lblStreetNameWorkAddress = new javax.swing.JLabel();
        txtUnitNumberWorkAddress = new javax.swing.JTextField();
        txtCityNameWorkAddress = new javax.swing.JTextField();
        lblUnitNumberWorkAddress = new javax.swing.JLabel();
        txtStateNameWorkAddress = new javax.swing.JTextField();
        lblCityNameWorkAddress = new javax.swing.JLabel();
        txtPhoneNumberWorkAddress = new javax.swing.JTextField();
        lblStateNameWorkAddress = new javax.swing.JLabel();
        txtZipCodeWorkAddress = new javax.swing.JTextField();
        lblZipCodeWorkAddress = new javax.swing.JLabel();
        lblPhoneNumberWorkAddress = new javax.swing.JLabel();
        btnAddNewPerson = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 0, 102));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102)));

        lblAddNewPerson.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        lblAddNewPerson.setForeground(java.awt.Color.white);
        lblAddNewPerson.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddNewPerson.setText("Add New Person");
        lblAddNewPerson.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153)));

        btnBack.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblFirstName.setBackground(new java.awt.Color(0, 102, 153));
        lblFirstName.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName.setText("First Name");

        txtFirstName.setForeground(new java.awt.Color(0, 0, 102));

        lblGender.setBackground(new java.awt.Color(0, 102, 153));
        lblGender.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblGender.setForeground(new java.awt.Color(255, 255, 255));
        lblGender.setText("Gender");

        txtGender.setForeground(new java.awt.Color(0, 0, 102));

        lblDateOfBirth.setBackground(new java.awt.Color(0, 102, 153));
        lblDateOfBirth.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblDateOfBirth.setForeground(new java.awt.Color(255, 255, 255));
        lblDateOfBirth.setText("Date of Birth");

        txtDateOfBirth.setForeground(new java.awt.Color(0, 0, 102));

        lblSsn.setBackground(new java.awt.Color(0, 102, 153));
        lblSsn.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblSsn.setForeground(new java.awt.Color(255, 255, 255));
        lblSsn.setText("SSN");

        txtSsn.setForeground(new java.awt.Color(0, 0, 102));

        lblLastName.setBackground(new java.awt.Color(0, 102, 153));
        lblLastName.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblLastName.setText("Last Name");

        txtPhoneNumber.setForeground(new java.awt.Color(0, 0, 102));

        lblAge.setBackground(new java.awt.Color(0, 102, 153));
        lblAge.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblAge.setForeground(new java.awt.Color(255, 255, 255));
        lblAge.setText("Age");

        txtAge.setForeground(new java.awt.Color(0, 0, 102));

        lblPhoneNumber.setBackground(new java.awt.Color(0, 102, 153));
        lblPhoneNumber.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoneNumber.setText("Phone Number");

        txtLastName.setForeground(new java.awt.Color(0, 0, 102));

        lblSalary.setBackground(new java.awt.Color(0, 102, 153));
        lblSalary.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblSalary.setForeground(new java.awt.Color(255, 255, 255));
        lblSalary.setText("Salary");

        txtSalary.setForeground(new java.awt.Color(0, 0, 102));

        lblHomeAddress.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        lblHomeAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblHomeAddress.setText("Home Address");
        lblHomeAddress.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 255), new java.awt.Color(255, 204, 255), new java.awt.Color(255, 204, 255), new java.awt.Color(255, 204, 255)));

        lblWorkAddress.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        lblWorkAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblWorkAddress.setText("Work Address");
        lblWorkAddress.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 255), new java.awt.Color(255, 204, 255), new java.awt.Color(255, 204, 255), new java.awt.Color(255, 204, 255)));

        lblStreetNameHomeAddress.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblStreetNameHomeAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblStreetNameHomeAddress.setText("Street Name");

        lblUnitNumberHomeAddress.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblUnitNumberHomeAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblUnitNumberHomeAddress.setText("Unit Number");

        lblCityNameHomeAddress.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblCityNameHomeAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblCityNameHomeAddress.setText("City Name");

        lblStateNameHomeAddress.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblStateNameHomeAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblStateNameHomeAddress.setText("State Name");

        lblZipCodeHomeAddress.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblZipCodeHomeAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblZipCodeHomeAddress.setText("Zip Code");

        lblPhoneNumberHomeAddress.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblPhoneNumberHomeAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoneNumberHomeAddress.setText("Phone Number");

        lblStreetNameWorkAddress.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblStreetNameWorkAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblStreetNameWorkAddress.setText("Street Name");

        lblUnitNumberWorkAddress.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblUnitNumberWorkAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblUnitNumberWorkAddress.setText("Unit Number");

        lblCityNameWorkAddress.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblCityNameWorkAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblCityNameWorkAddress.setText("City Name");

        lblStateNameWorkAddress.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblStateNameWorkAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblStateNameWorkAddress.setText("State Name");

        lblZipCodeWorkAddress.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblZipCodeWorkAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblZipCodeWorkAddress.setText("Zip Code");

        lblPhoneNumberWorkAddress.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblPhoneNumberWorkAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoneNumberWorkAddress.setText("Phone Number");

        btnAddNewPerson.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        btnAddNewPerson.setText("Add New Person");
        btnAddNewPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewPersonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblAddNewPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(btnAddNewPerson)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblStreetNameHomeAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblUnitNumberHomeAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCityNameHomeAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblStateNameHomeAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblZipCodeHomeAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPhoneNumberHomeAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(txtStreetNameHomeAddress))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtStateNameHomeAddress)
                                            .addComponent(txtUnitNumberHomeAddress)
                                            .addComponent(txtPhoneNumberHomeAddress)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtCityNameHomeAddress)
                                                    .addComponent(txtZipCodeHomeAddress))))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblWorkAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(22, 22, 22))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblStreetNameWorkAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblUnitNumberWorkAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCityNameWorkAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblStateNameWorkAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblZipCodeWorkAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPhoneNumberWorkAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(txtStreetNameWorkAddress))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtStateNameWorkAddress)
                                            .addComponent(txtUnitNumberWorkAddress)
                                            .addComponent(txtPhoneNumberWorkAddress)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtCityNameWorkAddress)
                                                    .addComponent(txtZipCodeWorkAddress))))))
                                .addContainerGap())))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAge, lblDateOfBirth, lblFirstName, lblGender, lblLastName, lblPhoneNumber, lblSalary, lblSsn, txtAge, txtDateOfBirth, txtFirstName, txtGender, txtLastName, txtPhoneNumber, txtSalary, txtSsn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddNewPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDateOfBirth)
                    .addComponent(lblLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSsn)
                    .addComponent(lblPhoneNumber)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSalary)
                    .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAge)
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHomeAddress)
                    .addComponent(lblWorkAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStreetNameHomeAddress)
                            .addComponent(txtStreetNameHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUnitNumberHomeAddress)
                            .addComponent(txtUnitNumberHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCityNameHomeAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblStateNameHomeAddress))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCityNameHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtStateNameHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblZipCodeHomeAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPhoneNumberHomeAddress))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtZipCodeHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPhoneNumberHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStreetNameWorkAddress)
                            .addComponent(txtStreetNameWorkAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUnitNumberWorkAddress)
                            .addComponent(txtUnitNumberWorkAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCityNameWorkAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblStateNameWorkAddress))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCityNameWorkAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtStateNameWorkAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblZipCodeWorkAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPhoneNumberWorkAddress))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtZipCodeWorkAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPhoneNumberWorkAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddNewPerson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblAge, lblDateOfBirth, lblFirstName, lblGender, lblLastName, lblPhoneNumber, lblSalary, lblSsn, txtAge, txtDateOfBirth, txtFirstName, txtGender, txtLastName, txtPhoneNumber, txtSalary, txtSsn});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblCityNameHomeAddress, lblPhoneNumberHomeAddress, lblStateNameHomeAddress, lblStreetNameHomeAddress, lblUnitNumberHomeAddress, lblZipCodeHomeAddress, txtCityNameHomeAddress, txtPhoneNumberHomeAddress, txtStateNameHomeAddress, txtStreetNameHomeAddress, txtUnitNumberHomeAddress, txtZipCodeHomeAddress});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblCityNameWorkAddress, lblPhoneNumberWorkAddress, lblStateNameWorkAddress, lblStreetNameWorkAddress, lblUnitNumberWorkAddress, lblZipCodeWorkAddress, txtCityNameWorkAddress, txtPhoneNumberWorkAddress, txtStateNameWorkAddress, txtStreetNameWorkAddress, txtUnitNumberWorkAddress, txtZipCodeWorkAddress});

    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddNewPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewPersonActionPerformed
        // TODO add your handling code here:
        
        long socialSecurityNumber;
        int age;
        char gender;
        double salary;
        
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String phoneNumber = txtPhoneNumber.getText();
        String dateOfBirth = txtDateOfBirth.getText();
        
        Address homeAddress = new Address();
        homeAddress.setStreetName(txtStreetNameHomeAddress.getText());
        homeAddress.setUnitNumber(txtUnitNumberHomeAddress.getText());
        homeAddress.setCityName(txtCityNameHomeAddress.getText());
        homeAddress.setStateName(txtStateNameHomeAddress.getText());
        homeAddress.setZipCode(txtZipCodeHomeAddress.getText());
        homeAddress.setPhoneNumber(txtPhoneNumberHomeAddress.getText());
        
        Address workAddress = new Address();
        workAddress.setStreetName(txtStreetNameWorkAddress.getText());
        workAddress.setUnitNumber(txtUnitNumberWorkAddress.getText());
        workAddress.setCityName(txtCityNameWorkAddress.getText());
        workAddress.setStateName(txtStateNameWorkAddress.getText());
        workAddress.setZipCode(txtZipCodeWorkAddress.getText());
        workAddress.setPhoneNumber(txtPhoneNumberWorkAddress.getText());
        
        if (firstName.isBlank() || lastName.isBlank() || phoneNumber.isBlank() || dateOfBirth.isBlank() || txtSsn.getText().isBlank()
            || txtAge.getText().isBlank() || txtGender.getText().isBlank() || txtSalary.getText().isBlank() || txtStreetNameHomeAddress.getText().isBlank() || txtUnitNumberHomeAddress.getText().isBlank()
            || txtCityNameHomeAddress.getText().isBlank() || txtStateNameHomeAddress.getText().isBlank() || txtZipCodeHomeAddress.getText().isBlank() 
            || txtPhoneNumberHomeAddress.getText().isBlank() || txtStreetNameWorkAddress.getText().isBlank() || txtUnitNumberWorkAddress.getText().isBlank()
            || txtCityNameWorkAddress.getText().isBlank() || txtStateNameWorkAddress.getText().isBlank() || txtZipCodeWorkAddress.getText().isBlank() 
            || txtPhoneNumberWorkAddress.getText().isBlank())
        {
            JOptionPane.showMessageDialog(this, "All fields are mandatory.", "Error", JOptionPane.ERROR_MESSAGE);
            //pause until the user closes the dialog.
            return;
        }
        try {
            socialSecurityNumber = Long.parseLong(txtSsn.getText());
            age = Integer.parseInt(txtAge.getText());
            salary = Double.parseDouble(txtSalary.getText());
            gender = txtGender.getText().charAt(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the input.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Person p = personDirectory.addNewPerson();
        
        p.setFirstName(firstName);
        p.setLastName(lastName);
        p.setPhoneNumber(phoneNumber);
        p.setDateOfBirth(dateOfBirth);
        p.setSocialSecurityNumber(socialSecurityNumber);
        p.setAge(age);
        p.setGender(gender);
        p.setSalary(salary);
        p.setHomeAddress(homeAddress);
        p.setWorkAddress(workAddress);
        
        
        JOptionPane.showMessageDialog(this, "User Account successfully created.", "Information", JOptionPane.INFORMATION_MESSAGE);
        
        txtFirstName.setText("");
        txtLastName.setText("");
        txtPhoneNumber.setText("");
        txtDateOfBirth.setText("");
        txtSsn.setText("");
        txtAge.setText("");
        txtGender.setText("");
        txtSalary.setText("");
        txtStreetNameHomeAddress.setText("");
        txtUnitNumberHomeAddress.setText("");
        txtCityNameHomeAddress.setText("");
        txtStateNameHomeAddress.setText("");
        txtZipCodeHomeAddress.setText("");
        txtPhoneNumberHomeAddress.setText("");
        txtStreetNameWorkAddress.setText("");
        txtUnitNumberWorkAddress.setText("");
        txtCityNameWorkAddress.setText("");
        txtStateNameWorkAddress.setText("");
        txtZipCodeWorkAddress.setText("");
        txtPhoneNumberWorkAddress.setText("");
    }//GEN-LAST:event_btnAddNewPersonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewPerson;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblAddNewPerson;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCityNameHomeAddress;
    private javax.swing.JLabel lblCityNameWorkAddress;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHomeAddress;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPhoneNumberHomeAddress;
    private javax.swing.JLabel lblPhoneNumberWorkAddress;
    private javax.swing.JLabel lblSalary;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblStateNameHomeAddress;
    private javax.swing.JLabel lblStateNameWorkAddress;
    private javax.swing.JLabel lblStreetNameHomeAddress;
    private javax.swing.JLabel lblStreetNameWorkAddress;
    private javax.swing.JLabel lblUnitNumberHomeAddress;
    private javax.swing.JLabel lblUnitNumberWorkAddress;
    private javax.swing.JLabel lblWorkAddress;
    private javax.swing.JLabel lblZipCodeHomeAddress;
    private javax.swing.JLabel lblZipCodeWorkAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCityNameHomeAddress;
    private javax.swing.JTextField txtCityNameWorkAddress;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtPhoneNumberHomeAddress;
    private javax.swing.JTextField txtPhoneNumberWorkAddress;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtStateNameHomeAddress;
    private javax.swing.JTextField txtStateNameWorkAddress;
    private javax.swing.JTextField txtStreetNameHomeAddress;
    private javax.swing.JTextField txtStreetNameWorkAddress;
    private javax.swing.JTextField txtUnitNumberHomeAddress;
    private javax.swing.JTextField txtUnitNumberWorkAddress;
    private javax.swing.JTextField txtZipCodeHomeAddress;
    private javax.swing.JTextField txtZipCodeWorkAddress;
    // End of variables declaration//GEN-END:variables
}
