/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.UserManager;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.PersonDirectory;

/**
 *
 * @author Reetika
 */
public class UserMngWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    PersonDirectory personDirectory;

    /**
     * Creates new form UserMngWorkAreaJPanel
     */
    public UserMngWorkAreaJPanel(JPanel container, PersonDirectory directory) {
        initComponents();
        
        userProcessContainer = container;
        personDirectory = directory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddNewPerson = new javax.swing.JButton();
        lblProfileManagementArea = new javax.swing.JLabel();
        btnSearchAndManage = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 0, 102));

        btnAddNewPerson.setBackground(new java.awt.Color(0, 102, 102));
        btnAddNewPerson.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnAddNewPerson.setText("Add New Person");
        btnAddNewPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewPersonActionPerformed(evt);
            }
        });

        lblProfileManagementArea.setBackground(new java.awt.Color(153, 255, 255));
        lblProfileManagementArea.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        lblProfileManagementArea.setForeground(new java.awt.Color(255, 255, 255));
        lblProfileManagementArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfileManagementArea.setText("Profile Management Area");

        btnSearchAndManage.setBackground(new java.awt.Color(0, 102, 102));
        btnSearchAndManage.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnSearchAndManage.setText("Search and Manage");
        btnSearchAndManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAndManageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblProfileManagementArea, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnAddNewPerson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearchAndManage)
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProfileManagementArea, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNewPerson)
                    .addComponent(btnSearchAndManage))
                .addContainerGap(322, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewPersonActionPerformed
        // TODO add your handling code here:
        NewPersonJPanel panel = new NewPersonJPanel(userProcessContainer, personDirectory);
        userProcessContainer.add("NewPersonJPanel", panel);
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddNewPersonActionPerformed

    private void btnSearchAndManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAndManageActionPerformed
        // TODO add your handling code here:
        ManageAccountJPanel panel = new ManageAccountJPanel(userProcessContainer, personDirectory);
        userProcessContainer.add("ManageAccountJPanel", panel);
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSearchAndManageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewPerson;
    private javax.swing.JButton btnSearchAndManage;
    private javax.swing.JLabel lblProfileManagementArea;
    // End of variables declaration//GEN-END:variables
}
