/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.UserManager;

/**
 *
 * @author Reetika
 */
public class ViewAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAccountJPanel
     */
    public ViewAccountJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdate = new javax.swing.JButton();
        lblViewAccount = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtZipCodeHomeAddress = new javax.swing.JTextField();
        txtStreetNameWorkAddress = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        lblStreetNameWorkAddress = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        txtUnitNumberWorkAddress = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtCityNameWorkAddress = new javax.swing.JTextField();
        lblPhoneNumber = new javax.swing.JLabel();
        lblUnitNumberWorkAddress = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtStateNameWorkAddress = new javax.swing.JTextField();
        lblSalary = new javax.swing.JLabel();
        lblCityNameWorkAddress = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        txtPhoneNumberWorkAddress = new javax.swing.JTextField();
        lblHomeAddress = new javax.swing.JLabel();
        lblStateNameWorkAddress = new javax.swing.JLabel();
        lblWorkAddress = new javax.swing.JLabel();
        lblStreetNameHomeAddress = new javax.swing.JLabel();
        txtZipCodeWorkAddress = new javax.swing.JTextField();
        lblZipCodeWorkAddress = new javax.swing.JLabel();
        lblUnitNumberHomeAddress = new javax.swing.JLabel();
        lblPhoneNumberWorkAddress = new javax.swing.JLabel();
        lblCityNameHomeAddress = new javax.swing.JLabel();
        lblStateNameHomeAddress = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblZipCodeHomeAddress = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblPhoneNumberHomeAddress = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        txtStreetNameHomeAddress = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        txtUnitNumberHomeAddress = new javax.swing.JTextField();
        lblDateOfBirth = new javax.swing.JLabel();
        txtCityNameHomeAddress = new javax.swing.JTextField();
        txtDateOfBirth = new javax.swing.JTextField();
        txtStateNameHomeAddress = new javax.swing.JTextField();
        lblSsn = new javax.swing.JLabel();
        txtPhoneNumberHomeAddress = new javax.swing.JTextField();
        txtSsn = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 0, 102));

        btnUpdate.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        btnUpdate.setText("Update");

        lblViewAccount.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        lblViewAccount.setForeground(java.awt.Color.white);
        lblViewAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewAccount.setText("View Account");
        lblViewAccount.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153)));

        btnBack.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        btnSave.setText("Save");

        txtPhoneNumber.setForeground(new java.awt.Color(0, 0, 102));

        lblStreetNameWorkAddress.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblStreetNameWorkAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblStreetNameWorkAddress.setText("Street Name");

        lblAge.setBackground(new java.awt.Color(0, 102, 153));
        lblAge.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblAge.setForeground(new java.awt.Color(255, 255, 255));
        lblAge.setText("Age");

        txtAge.setForeground(new java.awt.Color(0, 0, 102));

        lblPhoneNumber.setBackground(new java.awt.Color(0, 102, 153));
        lblPhoneNumber.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoneNumber.setText("Phone Number");

        lblUnitNumberWorkAddress.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblUnitNumberWorkAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblUnitNumberWorkAddress.setText("Unit Number");

        txtLastName.setForeground(new java.awt.Color(0, 0, 102));

        lblSalary.setBackground(new java.awt.Color(0, 102, 153));
        lblSalary.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblSalary.setForeground(new java.awt.Color(255, 255, 255));
        lblSalary.setText("Salary");

        lblCityNameWorkAddress.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblCityNameWorkAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblCityNameWorkAddress.setText("City Name");

        txtSalary.setForeground(new java.awt.Color(0, 0, 102));

        lblHomeAddress.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        lblHomeAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblHomeAddress.setText("Home Address");
        lblHomeAddress.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 255), new java.awt.Color(255, 204, 255), new java.awt.Color(255, 204, 255), new java.awt.Color(255, 204, 255)));

        lblStateNameWorkAddress.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblStateNameWorkAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblStateNameWorkAddress.setText("State Name");

        lblWorkAddress.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        lblWorkAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblWorkAddress.setText("Work Address");
        lblWorkAddress.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 255), new java.awt.Color(255, 204, 255), new java.awt.Color(255, 204, 255), new java.awt.Color(255, 204, 255)));

        lblStreetNameHomeAddress.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblStreetNameHomeAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblStreetNameHomeAddress.setText("Street Name");

        lblZipCodeWorkAddress.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblZipCodeWorkAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblZipCodeWorkAddress.setText("Zip Code");

        lblUnitNumberHomeAddress.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblUnitNumberHomeAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblUnitNumberHomeAddress.setText("Unit Number");

        lblPhoneNumberWorkAddress.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblPhoneNumberWorkAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoneNumberWorkAddress.setText("Phone Number");

        lblCityNameHomeAddress.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblCityNameHomeAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblCityNameHomeAddress.setText("City Name");

        lblStateNameHomeAddress.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblStateNameHomeAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblStateNameHomeAddress.setText("State Name");

        lblFirstName.setBackground(new java.awt.Color(0, 102, 153));
        lblFirstName.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName.setText("First Name");

        lblZipCodeHomeAddress.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblZipCodeHomeAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblZipCodeHomeAddress.setText("Zip Code");

        txtFirstName.setForeground(new java.awt.Color(0, 0, 102));

        lblPhoneNumberHomeAddress.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblPhoneNumberHomeAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoneNumberHomeAddress.setText("Phone Number");

        lblGender.setBackground(new java.awt.Color(0, 102, 153));
        lblGender.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblGender.setForeground(new java.awt.Color(255, 255, 255));
        lblGender.setText("Gender");

        txtGender.setForeground(new java.awt.Color(0, 0, 102));

        lblDateOfBirth.setBackground(new java.awt.Color(0, 102, 153));
        lblDateOfBirth.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblDateOfBirth.setForeground(new java.awt.Color(255, 255, 255));
        lblDateOfBirth.setText("Date of Birth");

        txtDateOfBirth.setForeground(new java.awt.Color(0, 0, 102));

        lblSsn.setBackground(new java.awt.Color(0, 102, 153));
        lblSsn.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblSsn.setForeground(new java.awt.Color(255, 255, 255));
        lblSsn.setText("SSN");

        txtSsn.setForeground(new java.awt.Color(0, 0, 102));

        lblLastName.setBackground(new java.awt.Color(0, 102, 153));
        lblLastName.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblLastName.setText("Last Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblViewAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addContainerGap(577, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 243, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addGap(230, 230, 230))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(16, 16, 16)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(16, 16, 16))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblStreetNameHomeAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblUnitNumberHomeAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCityNameHomeAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblStateNameHomeAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblZipCodeHomeAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblPhoneNumberHomeAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(14, 14, 14)
                                            .addComponent(txtStreetNameHomeAddress))
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtStateNameHomeAddress)
                                                .addComponent(txtUnitNumberHomeAddress)
                                                .addComponent(txtPhoneNumberHomeAddress)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(2, 2, 2)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtCityNameHomeAddress)
                                                        .addComponent(txtZipCodeHomeAddress))))))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblWorkAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(16, 16, 16))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblStreetNameWorkAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblUnitNumberWorkAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCityNameWorkAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblStateNameWorkAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblZipCodeWorkAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblPhoneNumberWorkAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(14, 14, 14)
                                            .addComponent(txtStreetNameWorkAddress))
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtStateNameWorkAddress)
                                                .addComponent(txtUnitNumberWorkAddress)
                                                .addComponent(txtPhoneNumberWorkAddress)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(2, 2, 2)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtCityNameWorkAddress)
                                                        .addComponent(txtZipCodeWorkAddress))))))))))
                    .addGap(14, 14, 14)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblViewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(405, 405, 405)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnSave))
                .addGap(9, 9, 9)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(80, 80, 80)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFirstName)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblGender))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDateOfBirth)
                        .addComponent(lblLastName))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSsn)
                        .addComponent(lblPhoneNumber)
                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblSalary)
                        .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAge)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHomeAddress)
                        .addComponent(lblWorkAddress))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblStreetNameHomeAddress)
                                .addComponent(txtStreetNameHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblUnitNumberHomeAddress)
                                .addComponent(txtUnitNumberHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCityNameHomeAddress)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblStateNameHomeAddress))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtCityNameHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtStateNameHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblZipCodeHomeAddress)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblPhoneNumberHomeAddress))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtZipCodeHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPhoneNumberHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblStreetNameWorkAddress)
                                .addComponent(txtStreetNameWorkAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblUnitNumberWorkAddress)
                                .addComponent(txtUnitNumberWorkAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCityNameWorkAddress)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblStateNameWorkAddress))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtCityNameWorkAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtStateNameWorkAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblZipCodeWorkAddress)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblPhoneNumberWorkAddress))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtZipCodeWorkAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPhoneNumberWorkAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap(87, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCityNameHomeAddress;
    private javax.swing.JLabel lblCityNameWorkAddress;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHomeAddress;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPhoneNumberHomeAddress;
    private javax.swing.JLabel lblPhoneNumberWorkAddress;
    private javax.swing.JLabel lblSalary;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblStateNameHomeAddress;
    private javax.swing.JLabel lblStateNameWorkAddress;
    private javax.swing.JLabel lblStreetNameHomeAddress;
    private javax.swing.JLabel lblStreetNameWorkAddress;
    private javax.swing.JLabel lblUnitNumberHomeAddress;
    private javax.swing.JLabel lblUnitNumberWorkAddress;
    private javax.swing.JLabel lblViewAccount;
    private javax.swing.JLabel lblWorkAddress;
    private javax.swing.JLabel lblZipCodeHomeAddress;
    private javax.swing.JLabel lblZipCodeWorkAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCityNameHomeAddress;
    private javax.swing.JTextField txtCityNameWorkAddress;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtPhoneNumberHomeAddress;
    private javax.swing.JTextField txtPhoneNumberWorkAddress;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtStateNameHomeAddress;
    private javax.swing.JTextField txtStateNameWorkAddress;
    private javax.swing.JTextField txtStreetNameHomeAddress;
    private javax.swing.JTextField txtStreetNameWorkAddress;
    private javax.swing.JTextField txtUnitNumberHomeAddress;
    private javax.swing.JTextField txtUnitNumberWorkAddress;
    private javax.swing.JTextField txtZipCodeHomeAddress;
    private javax.swing.JTextField txtZipCodeWorkAddress;
    // End of variables declaration//GEN-END:variables
}
